# Generated by Django 5.2.7 on 2025-11-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="preference",
            field=models.CharField(
                choices=[
                    ("general", "No preference / Balanced"),
                    ("culture_history", "Culture & History"),
                    ("city_shopping", "City Life & Shopping"),
                    ("adventure", "Adventure & Outdoors"),
                ],
                default="general",
                help_text="Overall tone for the generated itinerary.",
                max_length=32,
            ),
        ),
    ]
