# Generated by Django 5.2.7 on 2025-11-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_itinerary_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="activities",
            field=models.TextField(
                blank=True,
                help_text="Specific activities or experiences the traveler wants to prioritise.",
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="food_preferences",
            field=models.TextField(
                blank=True,
                help_text="Cuisine preferences, must-try drinks, and any dietary restrictions to keep in mind.",
            ),
        ),
    ]
