# Generated by Django 5.2.7 on 2025-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_itinerary_activities_itinerary_food_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="destination",
            field=models.TextField(),
        ),
    ]
